"""'添加富文本编辑器'

Revision ID: 96ac8acb1f6a
Revises: 955996901b47
Create Date: 2020-10-05 09:41:13.148275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ac8acb1f6a'
down_revision = '955996901b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body_html', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'published')
    op.drop_column('post', 'body_html')
    # ### end Alembic commands ###
